<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            // Super Admin
            [
                'name' => 'Super Admin',
                'first_name' => 'Super',
                'last_name' => 'Admin',
                'email' => 'admin@federgolf.it',
                'user_type' => 'super_admin',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
                'referee_code' => null,
                'level' => 'Nazionale',
                'gender' => 'mixed',
                'zone_id' => null,
                'is_active' => true,
            ],

            // National Admin
            [
                'name' => 'Admin Nazionale',
                'first_name' => 'Admin',
                'last_name' => 'Nazionale',
                'email' => 'admin.nazionale@federgolf.it',
                'user_type' => 'national_admin',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
                'referee_code' => 'NAZ001',
                'level' => 'Nazionale',
                'gender' => 'male',
                'zone_id' => null,
                'is_active' => true,
            ],

            // Zone Admins
            [
                'name' => 'Mario Rossi',
                'first_name' => 'Mario',
                'last_name' => 'Rossi',
                'email' => 'mario.rossi@szr1.it',
                'user_type' => 'admin',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
                'referee_code' => 'SZR1-001',
                'level' => 'Regionale',
                'gender' => 'male',
                'certified_date' => '2015-03-15',
                'zone_id' => 1, // SZR1
                'phone' => '+39 333 1234567',
                'city' => 'Torino',
                'address' => 'Via Roma 10',
                'postal_code' => '10100',
                'tax_code' => 'RSSMRA80A01L219K',
                'badge_number' => 'A001',
                'first_certification_date' => '2015-03-15',
                'last_renewal_date' => '2024-01-10',
                'expiry_date' => '2026-01-10',
                'experience_years' => 9,
                'total_tournaments' => 145,
                'tournaments_current_year' => 12,
                'is_active' => true,
                'club_member' => 'Golf Club Torino',
            ],

            [
                'name' => 'Laura Bianchi',
                'first_name' => 'Laura',
                'last_name' => 'Bianchi',
                'email' => 'laura.bianchi@szr2.it',
                'user_type' => 'admin',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
                'referee_code' => 'SZR2-001',
                'level' => 'Regionale',
                'gender' => 'female',
                'certified_date' => '2017-05-20',
                'zone_id' => 2, // SZR2
                'phone' => '+39 333 2345678',
                'city' => 'Milano',
                'address' => 'Via Montenapoleone 5',
                'postal_code' => '20121',
                'tax_code' => 'BNCLRA85E41F205Z',
                'badge_number' => 'A002',
                'first_certification_date' => '2017-05-20',
                'last_renewal_date' => '2024-02-15',
                'expiry_date' => '2026-02-15',
                'experience_years' => 7,
                'total_tournaments' => 98,
                'tournaments_current_year' => 8,
                'is_active' => true,
                'club_member' => 'Golf Milano',
            ],

            // Referees - National Level
            [
                'name' => 'Giuseppe Verdi',
                'first_name' => 'Giuseppe',
                'last_name' => 'Verdi',
                'email' => 'giuseppe.verdi@arbitro.it',
                'user_type' => 'referee',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
                'referee_code' => 'NAZ-042',
                'level' => 'Nazionale',
                'gender' => 'male',
                'certified_date' => '2010-06-10',
                'zone_id' => 3, // SZR3
                'phone' => '+39 333 3456789',
                'city' => 'Venezia',
                'address' => 'Calle Larga 22',
                'postal_code' => '30100',
                'tax_code' => 'VRDGPP75C10L736Y',
                'badge_number' => 'NAZ042',
                'first_certification_date' => '2010-06-10',
                'last_renewal_date' => '2024-06-01',
                'expiry_date' => '2026-06-01',
                'experience_years' => 14,
                'total_tournaments' => 278,
                'tournaments_current_year' => 18,
                'is_active' => true,
                'available_for_international' => true,
                'club_member' => 'Golf Club Venezia',
                'languages' => json_encode(['italiano', 'inglese', 'francese']),
                'specializations' => json_encode(['Campionati Nazionali', 'Gare Internazionali']),
            ],

            // Referees - Regional Level
            [
                'name' => 'Anna Ferrari',
                'first_name' => 'Anna',
                'last_name' => 'Ferrari',
                'email' => 'anna.ferrari@arbitro.it',
                'user_type' => 'referee',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
                'referee_code' => 'SZR4-015',
                'level' => 'Regionale',
                'gender' => 'female',
                'certified_date' => '2018-09-15',
                'zone_id' => 4, // SZR4
                'phone' => '+39 333 4567890',
                'city' => 'Bologna',
                'address' => 'Via Indipendenza 30',
                'postal_code' => '40121',
                'tax_code' => 'FRRNNA88P45A944M',
                'badge_number' => 'REG015',
                'first_certification_date' => '2018-09-15',
                'last_renewal_date' => '2024-03-20',
                'expiry_date' => '2026-03-20',
                'experience_years' => 6,
                'total_tournaments' => 72,
                'tournaments_current_year' => 9,
                'is_active' => true,
                'available_for_international' => false,
                'club_member' => 'Bologna Golf',
                'languages' => json_encode(['italiano', 'inglese']),
                'specializations' => json_encode(['Gare Giovanili', 'Tornei 36 buche']),
            ],

            [
                'name' => 'Marco Colombo',
                'first_name' => 'Marco',
                'last_name' => 'Colombo',
                'email' => 'marco.colombo@arbitro.it',
                'user_type' => 'referee',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
                'referee_code' => 'SZR5-028',
                'level' => 'Regionale',
                'gender' => 'male',
                'certified_date' => '2019-11-05',
                'zone_id' => 5, // SZR5
                'phone' => '+39 333 5678901',
                'city' => 'Firenze',
                'address' => 'Piazza Duomo 1',
                'postal_code' => '50122',
                'tax_code' => 'CLMMRC90S15D612H',
                'badge_number' => 'REG028',
                'first_certification_date' => '2019-11-05',
                'last_renewal_date' => '2024-05-10',
                'expiry_date' => '2026-05-10',
                'experience_years' => 5,
                'total_tournaments' => 58,
                'tournaments_current_year' => 7,
                'is_active' => true,
                'available_for_international' => false,
                'club_member' => 'Circolo Golf Ugolino',
                'languages' => json_encode(['italiano']),
                'specializations' => json_encode(['Tornei Regionali']),
            ],

            // Referees - 1° Livello
            [
                'name' => 'Francesca Romano',
                'first_name' => 'Francesca',
                'last_name' => 'Romano',
                'email' => 'francesca.romano@arbitro.it',
                'user_type' => 'referee',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
                'referee_code' => 'SZR6-073',
                'level' => '1_livello',
                'gender' => 'female',
                'certified_date' => '2021-04-12',
                'zone_id' => 6, // SZR6
                'phone' => '+39 333 6789012',
                'city' => 'Roma',
                'address' => 'Via Veneto 50',
                'postal_code' => '00187',
                'tax_code' => 'RMNFNC92D52H501E',
                'badge_number' => 'LV1073',
                'first_certification_date' => '2021-04-12',
                'last_renewal_date' => '2024-04-01',
                'expiry_date' => '2026-04-01',
                'experience_years' => 3,
                'total_tournaments' => 34,
                'tournaments_current_year' => 6,
                'is_active' => true,
                'available_for_international' => false,
                'club_member' => 'Olgiata Golf Club',
                'languages' => json_encode(['italiano', 'spagnolo']),
                'specializations' => json_encode(['Tornei 18 buche']),
            ],

            [
                'name' => 'Luca Conti',
                'first_name' => 'Luca',
                'last_name' => 'Conti',
                'email' => 'luca.conti@arbitro.it',
                'user_type' => 'referee',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
                'referee_code' => 'SZR7-089',
                'level' => '1_livello',
                'gender' => 'male',
                'certified_date' => '2022-06-20',
                'zone_id' => 7, // SZR7
                'phone' => '+39 333 7890123',
                'city' => 'Palermo',
                'address' => 'Via Libertà 100',
                'postal_code' => '90143',
                'tax_code' => 'CNTLCU95H20G273P',
                'badge_number' => 'LV1089',
                'first_certification_date' => '2022-06-20',
                'last_renewal_date' => '2024-06-15',
                'expiry_date' => '2026-06-15',
                'experience_years' => 2,
                'total_tournaments' => 21,
                'tournaments_current_year' => 4,
                'is_active' => true,
                'available_for_international' => false,
                'club_member' => 'Villa Airoldi Golf Club',
                'languages' => json_encode(['italiano']),
                'specializations' => json_encode(['Gare Giovanili']),
            ],

            // Aspirante
            [
                'name' => 'Sofia Marino',
                'first_name' => 'Sofia',
                'last_name' => 'Marino',
                'email' => 'sofia.marino@arbitro.it',
                'user_type' => 'referee',
                'password' => Hash::make('password'),
                'email_verified_at' => now(),
                'referee_code' => 'SZR2-112',
                'level' => 'Aspirante',
                'gender' => 'female',
                'certified_date' => '2024-02-10',
                'zone_id' => 2, // SZR2
                'phone' => '+39 333 8901234',
                'city' => 'Bergamo',
                'address' => 'Via XX Settembre 15',
                'postal_code' => '24122',
                'tax_code' => 'MRNSFO00A50A794F',
                'badge_number' => 'ASP112',
                'first_certification_date' => '2024-02-10',
                'last_renewal_date' => '2024-02-10',
                'expiry_date' => '2026-02-10',
                'experience_years' => 0,
                'total_tournaments' => 5,
                'tournaments_current_year' => 5,
                'is_active' => true,
                'available_for_international' => false,
                'club_member' => 'L\'Albenza Golf Club',
                'languages' => json_encode(['italiano']),
                'specializations' => json_encode(['Gare Giovanili']),
            ],
        ];

        foreach ($users as $userData) {
            User::create($userData);
        }

        $this->command->info('✓ Created '.count($users).' users');
    }
}
