graph TD
    A("Menu Assegnazioni") --> B("AssignmentController")
    B --> C("assignments/index.blade")
    C --> D("Create") & E("Show")
    D --> F("assignments/create.blade")
    E --> G("assignments/show.blade")
