graph TD
    A("Menu Circoli") --> B("ClubController")
    B --> C("clubs/index.blade")
    C --> D("Create") & E("Edit") & F("Show")
    D --> G("clubs/create.blade")
    E --> H("clubs/edit.blade")
    F --> I("clubs/show.blade")
